require: rubocop-rails

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - Gemfile
    - Rakefile
    - Guardfile
    - config.ru
    - vendor/bundle/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - spec/support/**/*
    - node_modules/**/*

Rails:
  Enabled: true

Naming/VariableNumber:
  EnforcedStyle: snake_case

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/LineLength:
  Max: 105

Metrics/MethodLength:
  Max: 20

Style/Lambda:
  EnforcedStyle: literal
