export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_HIKES_INIT = 'FETCH_HIKES_INIT';
export const FETCH_HIKES_SUCCESS = 'FETCH_HIKES_SUCCESS';
export const FETCH_HIKES_FAIL = 'FETCH_HIKES_FAIL';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
